# Generated by Django 5.0 on 2025-05-28 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('basic', 'базовый'), ('middle', 'средний'), ('high', 'высокий')], max_length=8)),
                ('text', models.TextField()),
                ('answer', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('is_registered', models.BooleanField(default=False)),
                ('exam_type', models.CharField(blank=True, choices=[('OGE', 'ОГЭ'), ('EGE', 'ЕГЭ')], max_length=3)),
                ('class_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('daily_level', models.CharField(choices=[('basic', 'базовый'), ('middle', 'средний'), ('high', 'высокий')], default='basic', max_length=8)),
                ('notify_time', models.TimeField(default='19:00')),
                ('subjects', models.ManyToManyField(blank=True, to='core.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8)),
                ('theory_md', models.TextField(blank=True)),
                ('video_link', models.URLField(blank=True)),
                ('train_file', models.FileField(blank=True, upload_to='trainers/')),
                ('answer_file', models.FileField(blank=True, upload_to='answers/')),
                ('is_active', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'unique_together': {('subject', 'number')},
            },
        ),
    ]
