# Generated by Django 5.0 on 2025-05-28 19:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('file', models.FileField(blank=True, upload_to='broadcasts/', verbose_name='Вложение')),
                ('target_filter', models.JSONField(verbose_name='Фильтр аудитории')),
                ('send_at', models.DateTimeField(verbose_name='Время отправки')),
                ('status', models.CharField(choices=[('pending', 'Запланировано'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='pending', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='task',
            name='theory_md',
        ),
        migrations.RemoveField(
            model_name='task',
            name='train_file',
        ),
        migrations.AddField(
            model_name='dailyquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='theory_file',
            field=models.FileField(blank=True, upload_to='theory/', verbose_name='Файл теории'),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=128, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='task',
            name='train_file1',
            field=models.FileField(blank=True, upload_to='trainers/', verbose_name='Тренажёр 1'),
        ),
        migrations.AddField(
            model_name='task',
            name='train_file2',
            field=models.FileField(blank=True, upload_to='trainers/', verbose_name='Тренажёр 2'),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='task',
            name='video_practice',
            field=models.URLField(blank=True, verbose_name='Видео-практика'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyquestion',
            name='answer',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='dailyquestion',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='Пояснение'),
        ),
        migrations.AlterField(
            model_name='dailyquestion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='dailyquestion',
            name='level',
            field=models.CharField(choices=[('basic', 'базовый'), ('middle', 'средний'), ('high', 'высокий')], max_length=8, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='dailyquestion',
            name='sent_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Отправлен'),
        ),
        migrations.AlterField(
            model_name='dailyquestion',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='dailyquestion',
            name='text',
            field=models.TextField(verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название предмета'),
        ),
        migrations.AlterField(
            model_name='task',
            name='answer_file',
            field=models.FileField(blank=True, upload_to='answers/', verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='task',
            name='number',
            field=models.CharField(max_length=8, verbose_name='Номер задания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='video_link',
            field=models.URLField(blank=True, verbose_name='Видео-теория'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='class_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='daily_level',
            field=models.CharField(choices=[('basic', 'базовый'), ('middle', 'средний'), ('high', 'высокий')], default='basic', max_length=8, verbose_name='Уровень ежедневных задач'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('OGE', 'ОГЭ'), ('EGE', 'ЕГЭ')], max_length=3, verbose_name='Экзамен'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='is_registered',
            field=models.BooleanField(default=False, verbose_name='Зарегистрирован'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='notify_time',
            field=models.TimeField(default='19:00', verbose_name='Время уведомлений'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='core.subject', verbose_name='Предметы'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='tg_id',
            field=models.BigIntegerField(unique=True, verbose_name='ID в Telegram'),
        ),
    ]
