# Generated by Django 5.0 on 2025-05-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_broadcast_remove_task_is_active_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='task',
            name='exam_type',
            field=models.CharField(choices=[('OGE', 'ОГЭ'), ('EGE', 'ЕГЭ')], default='OGE', max_length=3, verbose_name='Экзамен'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('subject', 'exam_type', 'number')},
        ),
    ]
