# Generated by Django 5.0 on 2025-05-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_task_unique_together_task_exam_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='task',
            name='subtype',
            field=models.CharField(blank=True, max_length=32, verbose_name='Тип задачи'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('subject', 'exam_type', 'number', 'subtype')},
        ),
    ]
