# Generated by Django 5.0 on 2025-05-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_task_unique_together_task_subtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='class_level',
            field=models.CharField(blank=True, default='9', max_length=10, verbose_name='Класс'),
            preserve_default=False,
        ),
    ]
