# Generated by Django 5.0 on 2025-05-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_tguser_class_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='days_left',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Дней до экзамена'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='subject_goals',
            field=models.JSONField(blank=True, default=dict, verbose_name='Желаемые баллы по предметам'),
        ),
    ]
