# Generated by Django 5.0 on 2025-05-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tguser_days_left_tguser_subject_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='trial_scores',
            field=models.JSONField(blank=True, default=dict, verbose_name='Пробные баллы по предметам'),
        ),
    ]
