# Generated by Django 5.0 on 2025-05-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tguser_trial_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='notify_time',
            field=models.TimeField(blank=True, default='19:00', null=True, verbose_name='Время уведомлений'),
        ),
    ]
