# Generated by Django 5.0 on 2025-05-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_tguser_notify_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('OGE', 'ОГЭ'), ('EGE', 'ЕГЭ')], max_length=3, verbose_name='Экзамен')),
                ('subject', models.CharField(max_length=64, verbose_name='Предмет')),
                ('desired_score', models.CharField(max_length=16, verbose_name='Желаемая оценка/балл')),
                ('trial_score', models.CharField(max_length=32, verbose_name='Баллы на пробнике')),
                ('text', models.TextField(verbose_name='Текст плана')),
            ],
            options={
                'verbose_name': 'План подготовки',
                'verbose_name_plural': 'Планы подготовки',
                'unique_together': {('exam_type', 'subject', 'desired_score', 'trial_score')},
            },
        ),
    ]
